real_estate_analysis/app/app/main/routes.py
from flask import render_template, Blueprint

main = Blueprint('main', __name__)

posts = [
    {
        'author': 'Jane Doe',
        'title': 'Blog Post 2',
        'content': 'Second Post Content',
        'date_posted': 'April 21, 2018'
    },
    {
        'author': 'Jane Doe',
        'title': 'Blog Post 1',
        'content': 'First Post Content',
        'date_posted': 'April 20, 2018'
    }
]


@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html')


@main.route('/about')
def about():
    return render_template('about.html', title='About')


@main.route('/faq')
def faq():
    return render_template('faq.html', title='FAQ')


@main.route('/pricing')
def pricing():
    return render_template('pricing.html', title='Pricing')


@main.route('/contact_us')
def contact_us():
    return render_template('contact_us.html', title='Contact Us')

real_estate_analysis/app/app/users/routes.py
import flask
import flask_login

from real_estate_analysis.app.app import db, bcrypt, models
from real_estate_analysis.app.app.users import forms
from real_estate_analysis.app.app.users.utils import send_reset_email

users = flask.Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if flask_login.current_user.is_authenticated:
        return flask.redirect(flask.url_for('main.home'))
    form = forms.RegistrationForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = models.User(username=form.username.data, email=form.email.data, password=hashed_pw)
        db.session.add(user)
        db.session.commit()
        flask.flash(message=f'Your account has been created. You are now able to log in', category='success')
        return flask.redirect(flask.url_for('users.login'))
    return flask.render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if flask_login.current_user.is_authenticated:
        return flask.redirect(flask.url_for('main.home'))
    form = forms.LoginForm()
    if form.validate_on_submit():
        user = models.User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            flask_login.login_user(user, remember=form.remember.data)
            next_page = flask.request.args.get('next')
            return flask.redirect(next_page) if next_page else flask.redirect(flask.url_for('main.home'))
        else:
            flask.flash(message='Login Unsuccessful. Please check email and password', category='danger')
    return flask.render_template('login.html', title='Login', form=form)


@users.route('/logout')
def logout():
    flask_login.logout_user()
    return flask.redirect(flask.url_for('main.home'))


@users.route('/account', methods=['GET', 'POST'])
@flask_login.login_required
def account():
    form = forms.UpdateAccountForm()
    if form.validate_on_submit():
        flask_login.current_user.username = form.username.data
        flask_login.current_user.email = form.email.data
        db.session.commit()
        flask.flash(message='Your account has been updated!', category='success')
        return flask.redirect(flask.url_for('users.account'))
    elif flask.request.method == 'GET':
        form.username.data = flask_login.current_user.username
        form.email.data = flask_login.current_user.email
    return flask.render_template('account.html', title='Account', form=form)


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if flask_login.current_user.is_authenticated:
        return flask.redirect(flask.url_for('main.home'))
    form = forms.RequestResetForm()
    if form.validate_on_submit():
        user = models.User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flask.flash(message='An email has been sent with reset instructions', category='info')
        return flask.redirect(flask.url_for('users.login'))
    return flask.render_template('reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if flask_login.current_user.is_authenticated:
        return flask.redirect(flask.url_for('main.home'))
    user = models.User.verify_reset_token(token)
    if user is None:
        flask.flash(message='That is an invalid/expired token', category='warning')
        return flask.redirect(flask.url_for('users.reset_request'))
    form = forms.ResetPasswordForm()
    if form.validate_on_submit():
        hashed_pw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_pw
        db.session.commit()
        flask.flash(message=f'Your password has been updated. You are now able to log in', category='success')
        return flask.redirect(flask.url_for('users.login'))
    return flask.render_template('reset_token.html', title='Reset Password', form=form)

real_estate_analysis/app/app/templates/about.html
{% extends "layout.html" %}
{% block hero %}
    <div class="hero page-inner">

		<div class="container">
			<div class="row justify-content-center align-items-center">
				<div class="col-lg-9 text-center mt-5">
					<h1 class="heading" data-aos="fade-up">About</h1>

					<nav aria-label="breadcrumb" data-aos="fade-up" data-aos-delay="200">
						<ol class="breadcrumb text-center justify-content-center">
							<li class="breadcrumb-item "><a href="index.html">Home</a></li>
							<li class="breadcrumb-item active text-white-50" aria-current="page">About</li>
						</ol>
					</nav>
				</div>
			</div>
		</div>
	</div>
{% endblock hero %}

{% block features %}
    <div class="section section-4 border-top">
		<div class="container">
			<div class="row justify-content-center  text-center mb-5">
				<div class="col-lg-6">
					<h2 class="font-weight-bold heading text-primary mb-4">We Bring Dream Homes To Reality</h2>
					<p class="text-black-50">Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam enim pariatur similique debitis vel nisi qui reprehenderit totam? Quod maiores.</p>
				</div>
			</div>
			<div class="row justify-content-between mb-5">
				<div class="col-lg-7 mb-5 mb-lg-0">
					<div class="img-about dots">
						<img src="static/images/hero_2.jpg" alt="Image" class="img-fluid">
					</div>
				</div>
				<div class="col-lg-4">
					<div class="d-flex feature-h">
						<span class="wrap-icon me-3">
							<span class="icon-home2"></span>
						</span>
						<div class="feature-text">
							<h3 class="heading">Quality properties</h3>
							<p class="text-black-50">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum iste.</p>
						</div>
					</div>

					<div class="d-flex feature-h">
						<span class="wrap-icon me-3">
							<span class="icon-person"></span>
						</span>
						<div class="feature-text">
							<h3 class="heading">Top rated agents</h3>
							<p class="text-black-50">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum iste.</p>
						</div>
					</div>

					<div class="d-flex feature-h">
						<span class="wrap-icon me-3">
							<span class="icon-security"></span>
						</span>
						<div class="feature-text">
							<h3 class="heading">Easy and safe</h3>
							<p class="text-black-50">Lorem ipsum dolor sit amet consectetur adipisicing elit. Nostrum iste.</p>
						</div>
					</div>
				</div>
			</div>
			<div class="row section-counter mt-5">
				<div class="col-6 col-sm-6 col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="300">
					<div class="counter-wrap mb-5 mb-lg-0">
						<span class="number"><span class="countup text-primary">2917</span></span>
						<span class="caption text-black-50"># of Buy Properties</span>
					</div>
				</div>
				<div class="col-6 col-sm-6 col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="400">
					<div class="counter-wrap mb-5 mb-lg-0">
						<span class="number"><span class="countup text-primary">3918</span></span>
						<span class="caption text-black-50"># of Sell Properties</span>
					</div>
				</div>
				<div class="col-6 col-sm-6 col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="500">
					<div class="counter-wrap mb-5 mb-lg-0">
						<span class="number"><span class="countup text-primary">38928</span></span>
						<span class="caption text-black-50"># of All Properties</span>
					</div>
				</div>
				<div class="col-6 col-sm-6 col-md-6 col-lg-3" data-aos="fade-up" data-aos-delay="600">
					<div class="counter-wrap mb-5 mb-lg-0">
						<span class="number"><span class="countup text-primary">1291</span></span>
						<span class="caption text-black-50"># of Agents</span>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock features %}

{% block team %}
    <div class="section sec-testimonials bg-light">
		<div class="container">
			<div class="row mb-5 align-items-center">
				<div class="col-md-6">
					<h2 class="font-weight-bold heading text-primary mb-4 mb-md-0">The Team</h2>
				</div>
				<div class="col-md-6 text-md-end">
					<div id="testimonial-nav">
						<span class="prev" data-controls="prev">Prev</span>

						<span class="next" data-controls="next">Next</span>
					</div>
				</div>
			</div>

			<div class="row">
				<div class="col-lg-4">

				</div>
			</div>
			<div class="testimonial-slider-wrap">
				<div class="testimonial-slider">
					<div class="item">
						<div class="testimonial">
							<img src="static/images/person_1.jpg" alt="Image" class="img-fluid rounded-circle w-25 mb-4">
							<h3 class="h5 text-primary">Erik Nyquist</h3>
							<p class="text-black-50">Machine Learning Engineer, CEO</p>

							<p>Text About CEO</p>

							<ul class="social list-unstyled list-inline dark-hover">
								<li class="list-inline-item"><a href="#"><span class="icon-twitter"></span></a></li>
								<li class="list-inline-item"><a href="#"><span class="icon-facebook"></span></a></li>
								<li class="list-inline-item"><a href="#"><span class="icon-linkedin"></span></a></li>
								<li class="list-inline-item"><a href="#"><span class="icon-instagram"></span></a></li>
							</ul>

						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock team %}

real_estate_analysis/app/app/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

real_estate_analysis/app/app/templates/contact_us.html
{% extends "layout.html" %}
{% block hero %}
  <div class="hero page-inner">

		<div class="container">
			<div class="row justify-content-center align-items-center">
				<div class="col-lg-9 text-center mt-5">
					<h1 class="heading" data-aos="fade-up">Contact Us</h1>

					<nav aria-label="breadcrumb" data-aos="fade-up" data-aos-delay="200">
						<ol class="breadcrumb text-center justify-content-center">
							<li class="breadcrumb-item "><a href="index.html">Home</a></li>
							<li class="breadcrumb-item active text-white-50" aria-current="page">Contact Us</li>
						</ol>
					</nav>


				</div>
			</div>


		</div>
	</div>
{% endblock hero %}

{% block content %}
    <div class="section section-4 border-top">
		<div class="container">
			<div class="row text-left mb-5">
				<div class="col-lg-6">
					<h2 class="font-weight-bold heading text-primary mb-4">Get In Touch</h2>
					<p class="text-black-50">Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam enim pariatur similique debitis vel nisi qui reprehenderit totam? Quod maiores.</p>
				</div>
			</div>

			<form class="row">

				<div class="mb-3 col-lg-6">
					<input type="text" class="form-control" placeholder="Name">
				</div>

				<div class="mb-3 col-lg-6">
					<input type="text" class="form-control" placeholder="Email Address">
				</div>

				<div class="mb-3 col-lg-6">
					<input type="text" class="form-control" placeholder="Subject">
				</div>

				<div class="mb-3 col-lg-6">
					<input type="text" class="form-control" placeholder="Phone">
				</div>

				<div class="mb-3 col-lg-12">
					<textarea name="" id="" cols="30" rows="5" class="form-control" placeholder="Write your message here..."></textarea>
				</div>

				<div class="mb-3 col-lg-12">
					<input type="text" class="btn btn-primary" value="Send Message">
				</div>
			</form>



		</div>
	</div>
{% endblock content %}

real_estate_analysis/app/app/templates/faq.html
{% extends "layout.html" %}
{% block content %}
    <h1>FAQ Page</h1>
{% endblock content %}

real_estate_analysis/app/app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@400;700&amp;display=swap" rel="stylesheet">
    <link rel="stylesheet" href="static/fonts/icomoon/style.css">
    <link rel="stylesheet" href="static/fonts/flaticon/font/flaticon.css">
    <link rel="stylesheet" href="static/css/tiny-slider.css">
    <link rel="stylesheet" href="static/css/aos.css">
    <link rel="stylesheet" href="static/css/style.css">

    <!-- Bootstrap CSS -->
<!--    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">-->

<!--    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">-->

    <!--    Favicon-->
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon/favicon.ico') }}">

    {% if title %}
        <title>Mikey the Model - {{ title }}</title>
    {% else %}
        <title>Mikey the Model</title>
    {% endif %}
</head>
<body>
    <div class="site-mobile-menu site-navbar-target">
		<div class="site-mobile-menu-header">
			<div class="site-mobile-menu-close">
				<span class="icofont-close js-menu-toggle"></span>
			</div>
		</div>
		<div class="site-mobile-menu-body"></div>
	</div>
    <nav class="site-nav">
		<div class="container">
			<div class="menu-bg-wrap">
				<div class="site-navigation">
					<a href="{{ url_for('main.home') }}" class="logo m-0 float-start">Mikey</a>

					<ul class="js-clone-nav d-none d-lg-inline-block text-start site-menu float-end">
						<li class="active"><a href="{{ url_for('main.home') }}">Home</a></li>
						<li class="has-children">
							<a href="#">Properties</a>
							<ul class="dropdown">
								<li><a href="#">Buy Property</a></li>
								<li><a href="#">Sell Property</a></li>
								<li class="has-children">
									<a href="#">Dropdown</a>
									<ul class="dropdown">
										<li><a href="#">Sub Menu One</a></li>
										<li><a href="#">Sub Menu Two</a></li>
										<li><a href="#">Sub Menu Three</a></li>
									</ul>
								</li>
							</ul>
						</li>
						<li><a href="{{ url_for('main.pricing') }}">Services</a></li>
						<li><a href="{{ url_for('main.about') }}">About</a></li>
						<li><a href="{{ url_for('main.contact_us') }}">Contact Us</a></li>
						{% if current_user.is_authenticated %}
							<li><a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a></li>
							<li><a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a></li>
						{% else %}
							<li><a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a></li>
							<li><a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a></li>
						{% endif %}
					</ul>

					<a href="#" class="burger me-auto float-end mt-1 site-menu-toggle js-menu-toggle d-inline-block d-lg-none" data-toggle="collapse" data-target="#main-navbar">
						<span></span>
					</a>

				</div>
			</div>
		</div>
	</nav>
	{% block hero %}{% endblock %}
	{% block features %}{% endblock %}
	{% block team %}{% endblock %}


<!--    <header class="site-header">-->
<!--      <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">-->
<!--        <div class="container">-->
<!--          <a class="navbar-brand mr-4" href="/">Company Name</a>-->
<!--          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">-->
<!--            <span class="navbar-toggler-icon"></span>-->
<!--          </button>-->
<!--          <div class="collapse navbar-collapse" id="navbarToggle">-->
<!--            <div class="navbar-nav mr-auto">-->
<!--                <a class="nav-item nav-link" href="{{ url_for('main.home') }}">Home</a>-->
<!--                <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>-->
<!--                <a class="nav-item nav-link" href="{{ url_for('main.pricing') }}">Pricing</a>-->
<!--                <a class="nav-item nav-link" href="{{ url_for('main.faq') }}">FAQ</a>-->
<!--            </div>-->
<!--             Navbar Right Side -->
<!--            <div class="navbar-nav">-->
<!--                {% if current_user.is_authenticated %}-->
<!--                    <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>-->
<!--                    <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>-->
<!--                {% else %}-->
<!--                    <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>-->
<!--                    <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>-->
<!--                {% endif %}-->
<!--            </div>-->
<!--          </div>-->
<!--        </div>-->
<!--      </nav>-->
<!--    </header>-->
    <main role="main" class="container">
      <div class="row">
        <div class="col-md-12">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block content %}{% endblock %}
        </div>
      </div>
    </main>
    <div class="site-footer">
		<div class="container">

			<div class="row">
				<div class="col-lg-4">
					<div class="widget">
						<h3>Contact</h3>
						<address>43 Raymouth Rd. Baltemoer, London 3910</address>
						<ul class="list-unstyled links">
							<li><a href="tel://11234567890">+1(123)-456-7890</a></li>
							<li><a href="tel://11234567890">+1(123)-456-7890</a></li>
							<li><a href="mailto:info@mydomain.com">info@mydomain.com</a></li>
						</ul>
					</div>
				</div>
			<div class="col-lg-4">
				<div class="widget">
					<h3>Sources</h3>
					<ul class="list-unstyled float-start links">
						<li><a href="#">About us</a></li>
						<li><a href="#">Services</a></li>
						<li><a href="#">Vision</a></li>
						<li><a href="#">Mission</a></li>
						<li><a href="#">Terms</a></li>
						<li><a href="#">Privacy</a></li>
					</ul>
					<ul class="list-unstyled float-start links">
						<li><a href="#">Partners</a></li>
						<li><a href="#">Business</a></li>
						<li><a href="#">Careers</a></li>
						<li><a href="#">Blog</a></li>
						<li><a href="#">FAQ</a></li>
						<li><a href="#">Creative</a></li>
					</ul>
				</div>
			</div>
			<div class="col-lg-4">
				<div class="widget">
					<h3>Links</h3>
					<ul class="list-unstyled links">
						<li><a href="#">Our Vision</a></li>
						<li><a href="#">About us</a></li>
						<li><a href="#">Contact us</a></li>
					</ul>
					<ul class="list-unstyled social">
						<li><a href="#"><span class="icon-instagram"></span></a></li>
						<li><a href="#"><span class="icon-twitter"></span></a></li>
						<li><a href="#"><span class="icon-facebook"></span></a></li>
						<li><a href="#"><span class="icon-linkedin"></span></a></li>
						<li><a href="#"><span class="icon-pinterest"></span></a></li>
						<li><a href="#"><span class="icon-dribbble"></span></a></li>
					</ul>
				</div>
			</div>
		</div>
		<div class="row mt-5">
			<div class="col-12 text-center">
				<p class="mb-0">Copyright ©<script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script><script>document.write(new Date().getFullYear());</script> All rights reserved</p>
			</div>
		</div>
		</div>
	</div>

    <!-- Preloader -->
    <div id="overlayer"></div>
    <div class="loader">
		<div class="spinner-border" role="status">
			<span class="visually-hidden">Loading...</span>
		</div>
	</div>
    <script src="static/js/bootstrap.bundle.min.js"></script>
    <script src="static/js/tiny-slider.js"></script>
    <script src="static/js/aos.js"></script>
    <script src="static/js/navbar.js"></script>
    <script src="static/js/counter.js"></script>
    <script src="static/js/custom.js"></script>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

real_estate_analysis/app/app/templates/login.html
{% extends "layout.html" %}
{% block hero %}
    <div class="hero page-inner">
		<div class="container">
			<div class="row justify-content-center align-items-center">
				<div class="col-lg-9 text-center mt-5">
					<h1 class="heading" data-aos="fade-up">Log In</h1>

					<nav aria-label="breadcrumb" data-aos="fade-up" data-aos-delay="200">
						<ol class="breadcrumb text-center justify-content-center">
							<li class="breadcrumb-item "><a href="index.html">Home</a></li>
							<li class="breadcrumb-item active text-white-50" aria-current="page">Log In</li>
						</ol>
					</nav>
				</div>
			</div>
		</div>
	</div>
{% endblock hero %}

{% block content %}
    <div class="section section-4 border-top">
        <div class="container">
            <div class="row text-left mb-5">
                <div class="col-lg-6">
                    <h2 class="font-weight-bold heading text-primary mb-4">Log In</h2>
                    <p class="text-black-50">Lorem ipsum dolor sit amet consectetur adipisicing elit. Numquam enim pariatur similique debitis vel nisi qui reprehenderit totam? Quod maiores.</p>
                </div>
            </div>

            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label text-black-50") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label text-black-50") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-check">
                        {{ form.remember(class='form-check-input') }}
                        {{ form.remember.label(class='form-check-label text-black-50') }}
                    </div>
                </fieldset>
                <div class="form-group">
                    {{ form.submit(class="btn btn-primary") }}
                    <small class="text-muted ml-2">
                        <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                    </small>
                </div>
            </form>
        </div>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

real_estate_analysis/app/app/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

real_estate_analysis/app/app/templates/reset_token.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label") }}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.confirm_password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.confirm_password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}